// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCommentUC is an autogenerated mock type for the CommentUC type
type MockCommentUC struct {
	mock.Mock
}

type MockCommentUC_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentUC) EXPECT() *MockCommentUC_Expecter {
	return &MockCommentUC_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, comment
func (_m *MockCommentUC) Add(ctx context.Context, comment models.Comment) (*models.Comment, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Comment) (*models.Comment, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Comment) *models.Comment); ok {
		r0 = rf(ctx, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCommentUC_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - comment models.Comment
func (_e *MockCommentUC_Expecter) Add(ctx interface{}, comment interface{}) *MockCommentUC_Add_Call {
	return &MockCommentUC_Add_Call{Call: _e.mock.On("Add", ctx, comment)}
}

func (_c *MockCommentUC_Add_Call) Run(run func(ctx context.Context, comment models.Comment)) *MockCommentUC_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Comment))
	})
	return _c
}

func (_c *MockCommentUC_Add_Call) Return(_a0 *models.Comment, _a1 error) *MockCommentUC_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_Add_Call) RunAndReturn(run func(context.Context, models.Comment) (*models.Comment, error)) *MockCommentUC_Add_Call {
	_c.Call.Return(run)
	return _c
}

// CheckAllowComments provides a mock function with given fields: ctx, postID
func (_m *MockCommentUC) CheckAllowComments(ctx context.Context, postID int64) (bool, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CheckAllowComments")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_CheckAllowComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAllowComments'
type MockCommentUC_CheckAllowComments_Call struct {
	*mock.Call
}

// CheckAllowComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockCommentUC_Expecter) CheckAllowComments(ctx interface{}, postID interface{}) *MockCommentUC_CheckAllowComments_Call {
	return &MockCommentUC_CheckAllowComments_Call{Call: _e.mock.On("CheckAllowComments", ctx, postID)}
}

func (_c *MockCommentUC_CheckAllowComments_Call) Run(run func(ctx context.Context, postID int64)) *MockCommentUC_CheckAllowComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCommentUC_CheckAllowComments_Call) Return(_a0 bool, _a1 error) *MockCommentUC_CheckAllowComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_CheckAllowComments_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *MockCommentUC_CheckAllowComments_Call {
	_c.Call.Return(run)
	return _c
}

// CheckParentExists provides a mock function with given fields: ctx, parentID
func (_m *MockCommentUC) CheckParentExists(ctx context.Context, parentID int64) (int64, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckParentExists")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, parentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_CheckParentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckParentExists'
type MockCommentUC_CheckParentExists_Call struct {
	*mock.Call
}

// CheckParentExists is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *MockCommentUC_Expecter) CheckParentExists(ctx interface{}, parentID interface{}) *MockCommentUC_CheckParentExists_Call {
	return &MockCommentUC_CheckParentExists_Call{Call: _e.mock.On("CheckParentExists", ctx, parentID)}
}

func (_c *MockCommentUC_CheckParentExists_Call) Run(run func(ctx context.Context, parentID int64)) *MockCommentUC_CheckParentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCommentUC_CheckParentExists_Call) Return(_a0 int64, _a1 error) *MockCommentUC_CheckParentExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_CheckParentExists_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockCommentUC_CheckParentExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetChild provides a mock function with given fields: ctx, parentID, afterCreatedAt, afterID, limit
func (_m *MockCommentUC) GetChild(ctx context.Context, parentID int64, afterCreatedAt *string, afterID int64, limit int32) ([]*models.Comment, error) {
	ret := _m.Called(ctx, parentID, afterCreatedAt, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetChild")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)); ok {
		return rf(ctx, parentID, afterCreatedAt, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) []*models.Comment); ok {
		r0 = rf(ctx, parentID, afterCreatedAt, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *string, int64, int32) error); ok {
		r1 = rf(ctx, parentID, afterCreatedAt, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_GetChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChild'
type MockCommentUC_GetChild_Call struct {
	*mock.Call
}

// GetChild is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - afterCreatedAt *string
//   - afterID int64
//   - limit int32
func (_e *MockCommentUC_Expecter) GetChild(ctx interface{}, parentID interface{}, afterCreatedAt interface{}, afterID interface{}, limit interface{}) *MockCommentUC_GetChild_Call {
	return &MockCommentUC_GetChild_Call{Call: _e.mock.On("GetChild", ctx, parentID, afterCreatedAt, afterID, limit)}
}

func (_c *MockCommentUC_GetChild_Call) Run(run func(ctx context.Context, parentID int64, afterCreatedAt *string, afterID int64, limit int32)) *MockCommentUC_GetChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*string), args[3].(int64), args[4].(int32))
	})
	return _c
}

func (_c *MockCommentUC_GetChild_Call) Return(_a0 []*models.Comment, _a1 error) *MockCommentUC_GetChild_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_GetChild_Call) RunAndReturn(run func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)) *MockCommentUC_GetChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildBatch provides a mock function with given fields: ctx, parentIDs
func (_m *MockCommentUC) GetChildBatch(ctx context.Context, parentIDs []int64) ([]*models.Comment, error) {
	ret := _m.Called(ctx, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetChildBatch")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*models.Comment, error)); ok {
		return rf(ctx, parentIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*models.Comment); ok {
		r0 = rf(ctx, parentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, parentIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_GetChildBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildBatch'
type MockCommentUC_GetChildBatch_Call struct {
	*mock.Call
}

// GetChildBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []int64
func (_e *MockCommentUC_Expecter) GetChildBatch(ctx interface{}, parentIDs interface{}) *MockCommentUC_GetChildBatch_Call {
	return &MockCommentUC_GetChildBatch_Call{Call: _e.mock.On("GetChildBatch", ctx, parentIDs)}
}

func (_c *MockCommentUC_GetChildBatch_Call) Run(run func(ctx context.Context, parentIDs []int64)) *MockCommentUC_GetChildBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockCommentUC_GetChildBatch_Call) Return(_a0 []*models.Comment, _a1 error) *MockCommentUC_GetChildBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_GetChildBatch_Call) RunAndReturn(run func(context.Context, []int64) ([]*models.Comment, error)) *MockCommentUC_GetChildBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootByPost provides a mock function with given fields: ctx, postID, afterCreatedAt, afterID, limit
func (_m *MockCommentUC) GetRootByPost(ctx context.Context, postID int64, afterCreatedAt *string, afterID int64, limit int32) ([]*models.Comment, error) {
	ret := _m.Called(ctx, postID, afterCreatedAt, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRootByPost")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)); ok {
		return rf(ctx, postID, afterCreatedAt, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) []*models.Comment); ok {
		r0 = rf(ctx, postID, afterCreatedAt, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *string, int64, int32) error); ok {
		r1 = rf(ctx, postID, afterCreatedAt, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_GetRootByPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootByPost'
type MockCommentUC_GetRootByPost_Call struct {
	*mock.Call
}

// GetRootByPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - afterCreatedAt *string
//   - afterID int64
//   - limit int32
func (_e *MockCommentUC_Expecter) GetRootByPost(ctx interface{}, postID interface{}, afterCreatedAt interface{}, afterID interface{}, limit interface{}) *MockCommentUC_GetRootByPost_Call {
	return &MockCommentUC_GetRootByPost_Call{Call: _e.mock.On("GetRootByPost", ctx, postID, afterCreatedAt, afterID, limit)}
}

func (_c *MockCommentUC_GetRootByPost_Call) Run(run func(ctx context.Context, postID int64, afterCreatedAt *string, afterID int64, limit int32)) *MockCommentUC_GetRootByPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*string), args[3].(int64), args[4].(int32))
	})
	return _c
}

func (_c *MockCommentUC_GetRootByPost_Call) Return(_a0 []*models.Comment, _a1 error) *MockCommentUC_GetRootByPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_GetRootByPost_Call) RunAndReturn(run func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)) *MockCommentUC_GetRootByPost_Call {
	_c.Call.Return(run)
	return _c
}

// TotalCount provides a mock function with given fields: ctx, postID
func (_m *MockCommentUC) TotalCount(ctx context.Context, postID int64) (int64, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for TotalCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUC_TotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCount'
type MockCommentUC_TotalCount_Call struct {
	*mock.Call
}

// TotalCount is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockCommentUC_Expecter) TotalCount(ctx interface{}, postID interface{}) *MockCommentUC_TotalCount_Call {
	return &MockCommentUC_TotalCount_Call{Call: _e.mock.On("TotalCount", ctx, postID)}
}

func (_c *MockCommentUC_TotalCount_Call) Run(run func(ctx context.Context, postID int64)) *MockCommentUC_TotalCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCommentUC_TotalCount_Call) Return(_a0 int64, _a1 error) *MockCommentUC_TotalCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUC_TotalCount_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockCommentUC_TotalCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentUC creates a new instance of MockCommentUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentUC {
	mock := &MockCommentUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
