// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPostUC is an autogenerated mock type for the PostUC type
type MockPostUC struct {
	mock.Mock
}

type MockPostUC_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostUC) EXPECT() *MockPostUC_Expecter {
	return &MockPostUC_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, afterCreatedAt, afterID, limit
func (_m *MockPostUC) Get(ctx context.Context, afterCreatedAt *string, afterID int64, limit int32) ([]*models.Post, error) {
	ret := _m.Called(ctx, afterCreatedAt, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, int64, int32) ([]*models.Post, error)); ok {
		return rf(ctx, afterCreatedAt, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, int64, int32) []*models.Post); ok {
		r0 = rf(ctx, afterCreatedAt, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, int64, int32) error); ok {
		r1 = rf(ctx, afterCreatedAt, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostUC_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPostUC_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - afterCreatedAt *string
//   - afterID int64
//   - limit int32
func (_e *MockPostUC_Expecter) Get(ctx interface{}, afterCreatedAt interface{}, afterID interface{}, limit interface{}) *MockPostUC_Get_Call {
	return &MockPostUC_Get_Call{Call: _e.mock.On("Get", ctx, afterCreatedAt, afterID, limit)}
}

func (_c *MockPostUC_Get_Call) Run(run func(ctx context.Context, afterCreatedAt *string, afterID int64, limit int32)) *MockPostUC_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(int64), args[3].(int32))
	})
	return _c
}

func (_c *MockPostUC_Get_Call) Return(_a0 []*models.Post, _a1 error) *MockPostUC_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostUC_Get_Call) RunAndReturn(run func(context.Context, *string, int64, int32) ([]*models.Post, error)) *MockPostUC_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, postID
func (_m *MockPostUC) GetByID(ctx context.Context, postID int64) (*models.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostUC_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPostUC_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockPostUC_Expecter) GetByID(ctx interface{}, postID interface{}) *MockPostUC_GetByID_Call {
	return &MockPostUC_GetByID_Call{Call: _e.mock.On("GetByID", ctx, postID)}
}

func (_c *MockPostUC_GetByID_Call) Run(run func(ctx context.Context, postID int64)) *MockPostUC_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPostUC_GetByID_Call) Return(_a0 *models.Post, _a1 error) *MockPostUC_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostUC_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Post, error)) *MockPostUC_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, post
func (_m *MockPostUC) Save(ctx context.Context, post models.Post) (models.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) (models.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) models.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostUC_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPostUC_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - post models.Post
func (_e *MockPostUC_Expecter) Save(ctx interface{}, post interface{}) *MockPostUC_Save_Call {
	return &MockPostUC_Save_Call{Call: _e.mock.On("Save", ctx, post)}
}

func (_c *MockPostUC_Save_Call) Run(run func(ctx context.Context, post models.Post)) *MockPostUC_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Post))
	})
	return _c
}

func (_c *MockPostUC_Save_Call) Return(_a0 models.Post, _a1 error) *MockPostUC_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostUC_Save_Call) RunAndReturn(run func(context.Context, models.Post) (models.Post, error)) *MockPostUC_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetCommentsAllowed provides a mock function with given fields: ctx, postID, allow
func (_m *MockPostUC) SetCommentsAllowed(ctx context.Context, postID int64, allow bool) (*models.Post, error) {
	ret := _m.Called(ctx, postID, allow)

	if len(ret) == 0 {
		panic("no return value specified for SetCommentsAllowed")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) (*models.Post, error)); ok {
		return rf(ctx, postID, allow)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) *models.Post); ok {
		r0 = rf(ctx, postID, allow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = rf(ctx, postID, allow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostUC_SetCommentsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommentsAllowed'
type MockPostUC_SetCommentsAllowed_Call struct {
	*mock.Call
}

// SetCommentsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - allow bool
func (_e *MockPostUC_Expecter) SetCommentsAllowed(ctx interface{}, postID interface{}, allow interface{}) *MockPostUC_SetCommentsAllowed_Call {
	return &MockPostUC_SetCommentsAllowed_Call{Call: _e.mock.On("SetCommentsAllowed", ctx, postID, allow)}
}

func (_c *MockPostUC_SetCommentsAllowed_Call) Run(run func(ctx context.Context, postID int64, allow bool)) *MockPostUC_SetCommentsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(bool))
	})
	return _c
}

func (_c *MockPostUC_SetCommentsAllowed_Call) Return(_a0 *models.Post, _a1 error) *MockPostUC_SetCommentsAllowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostUC_SetCommentsAllowed_Call) RunAndReturn(run func(context.Context, int64, bool) (*models.Post, error)) *MockPostUC_SetCommentsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// TotalCount provides a mock function with given fields: ctx
func (_m *MockPostUC) TotalCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TotalCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostUC_TotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCount'
type MockPostUC_TotalCount_Call struct {
	*mock.Call
}

// TotalCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPostUC_Expecter) TotalCount(ctx interface{}) *MockPostUC_TotalCount_Call {
	return &MockPostUC_TotalCount_Call{Call: _e.mock.On("TotalCount", ctx)}
}

func (_c *MockPostUC_TotalCount_Call) Run(run func(ctx context.Context)) *MockPostUC_TotalCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPostUC_TotalCount_Call) Return(_a0 int64, _a1 error) *MockPostUC_TotalCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostUC_TotalCount_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockPostUC_TotalCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostUC creates a new instance of MockPostUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostUC {
	mock := &MockPostUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
