// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GetPostById provides a mock function with given fields: ctx, postID
func (_m *MockUseCase) GetPostById(ctx context.Context, postID int64) (*models.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostById")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetPostById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostById'
type MockUseCase_GetPostById_Call struct {
	*mock.Call
}

// GetPostById is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockUseCase_Expecter) GetPostById(ctx interface{}, postID interface{}) *MockUseCase_GetPostById_Call {
	return &MockUseCase_GetPostById_Call{Call: _e.mock.On("GetPostById", ctx, postID)}
}

func (_c *MockUseCase_GetPostById_Call) Run(run func(ctx context.Context, postID int64)) *MockUseCase_GetPostById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUseCase_GetPostById_Call) Return(_a0 *models.Post, _a1 error) *MockUseCase_GetPostById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetPostById_Call) RunAndReturn(run func(context.Context, int64) (*models.Post, error)) *MockUseCase_GetPostById_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function with given fields: ctx, afterCreatedAt, afterID, limit
func (_m *MockUseCase) GetPosts(ctx context.Context, afterCreatedAt *string, afterID int64, limit int32) ([]*models.Post, error) {
	ret := _m.Called(ctx, afterCreatedAt, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []*models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, int64, int32) ([]*models.Post, error)); ok {
		return rf(ctx, afterCreatedAt, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, int64, int32) []*models.Post); ok {
		r0 = rf(ctx, afterCreatedAt, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, int64, int32) error); ok {
		r1 = rf(ctx, afterCreatedAt, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockUseCase_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - afterCreatedAt *string
//   - afterID int64
//   - limit int32
func (_e *MockUseCase_Expecter) GetPosts(ctx interface{}, afterCreatedAt interface{}, afterID interface{}, limit interface{}) *MockUseCase_GetPosts_Call {
	return &MockUseCase_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx, afterCreatedAt, afterID, limit)}
}

func (_c *MockUseCase_GetPosts_Call) Run(run func(ctx context.Context, afterCreatedAt *string, afterID int64, limit int32)) *MockUseCase_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(int64), args[3].(int32))
	})
	return _c
}

func (_c *MockUseCase_GetPosts_Call) Return(_a0 []*models.Post, _a1 error) *MockUseCase_GetPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetPosts_Call) RunAndReturn(run func(context.Context, *string, int64, int32) ([]*models.Post, error)) *MockUseCase_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// SavePost provides a mock function with given fields: ctx, _a1
func (_m *MockUseCase) SavePost(ctx context.Context, _a1 models.Post) (models.Post, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SavePost")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) (models.Post, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) models.Post); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Post) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_SavePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePost'
type MockUseCase_SavePost_Call struct {
	*mock.Call
}

// SavePost is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 models.Post
func (_e *MockUseCase_Expecter) SavePost(ctx interface{}, _a1 interface{}) *MockUseCase_SavePost_Call {
	return &MockUseCase_SavePost_Call{Call: _e.mock.On("SavePost", ctx, _a1)}
}

func (_c *MockUseCase_SavePost_Call) Run(run func(ctx context.Context, _a1 models.Post)) *MockUseCase_SavePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Post))
	})
	return _c
}

func (_c *MockUseCase_SavePost_Call) Return(_a0 models.Post, _a1 error) *MockUseCase_SavePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_SavePost_Call) RunAndReturn(run func(context.Context, models.Post) (models.Post, error)) *MockUseCase_SavePost_Call {
	_c.Call.Return(run)
	return _c
}

// SetPostCommentsAllowed provides a mock function with given fields: ctx, postID, allow
func (_m *MockUseCase) SetPostCommentsAllowed(ctx context.Context, postID string, allow bool) (*models.Post, error) {
	ret := _m.Called(ctx, postID, allow)

	if len(ret) == 0 {
		panic("no return value specified for SetPostCommentsAllowed")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Post, error)); ok {
		return rf(ctx, postID, allow)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *models.Post); ok {
		r0 = rf(ctx, postID, allow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, postID, allow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_SetPostCommentsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPostCommentsAllowed'
type MockUseCase_SetPostCommentsAllowed_Call struct {
	*mock.Call
}

// SetPostCommentsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - allow bool
func (_e *MockUseCase_Expecter) SetPostCommentsAllowed(ctx interface{}, postID interface{}, allow interface{}) *MockUseCase_SetPostCommentsAllowed_Call {
	return &MockUseCase_SetPostCommentsAllowed_Call{Call: _e.mock.On("SetPostCommentsAllowed", ctx, postID, allow)}
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) Run(run func(ctx context.Context, postID string, allow bool)) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) Return(_a0 *models.Post, _a1 error) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) RunAndReturn(run func(context.Context, string, bool) (*models.Post, error)) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// TotalCount provides a mock function with given fields: ctx
func (_m *MockUseCase) TotalCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TotalCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_TotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCount'
type MockUseCase_TotalCount_Call struct {
	*mock.Call
}

// TotalCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) TotalCount(ctx interface{}) *MockUseCase_TotalCount_Call {
	return &MockUseCase_TotalCount_Call{Call: _e.mock.On("TotalCount", ctx)}
}

func (_c *MockUseCase_TotalCount_Call) Run(run func(ctx context.Context)) *MockUseCase_TotalCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUseCase_TotalCount_Call) Return(_a0 int64, _a1 error) *MockUseCase_TotalCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_TotalCount_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockUseCase_TotalCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
