// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: ctx, in
func (_m *MockUseCase) AddComment(ctx context.Context, in models.AddCommentInput) (*models.Comment, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AddCommentInput) (*models.Comment, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AddCommentInput) *models.Comment); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AddCommentInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockUseCase_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.AddCommentInput
func (_e *MockUseCase_Expecter) AddComment(ctx interface{}, in interface{}) *MockUseCase_AddComment_Call {
	return &MockUseCase_AddComment_Call{Call: _e.mock.On("AddComment", ctx, in)}
}

func (_c *MockUseCase_AddComment_Call) Run(run func(ctx context.Context, in models.AddCommentInput)) *MockUseCase_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AddCommentInput))
	})
	return _c
}

func (_c *MockUseCase_AddComment_Call) Return(_a0 *models.Comment, _a1 error) *MockUseCase_AddComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_AddComment_Call) RunAndReturn(run func(context.Context, models.AddCommentInput) (*models.Comment, error)) *MockUseCase_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function with given fields: ctx, postID, first, after
func (_m *MockUseCase) GetComments(ctx context.Context, postID string, first *int32, after *string) (*models.CommentConnection, error) {
	ret := _m.Called(ctx, postID, first, after)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 *models.CommentConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *int32, *string) (*models.CommentConnection, error)); ok {
		return rf(ctx, postID, first, after)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *int32, *string) *models.CommentConnection); ok {
		r0 = rf(ctx, postID, first, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CommentConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *int32, *string) error); ok {
		r1 = rf(ctx, postID, first, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockUseCase_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - first *int32
//   - after *string
func (_e *MockUseCase_Expecter) GetComments(ctx interface{}, postID interface{}, first interface{}, after interface{}) *MockUseCase_GetComments_Call {
	return &MockUseCase_GetComments_Call{Call: _e.mock.On("GetComments", ctx, postID, first, after)}
}

func (_c *MockUseCase_GetComments_Call) Run(run func(ctx context.Context, postID string, first *int32, after *string)) *MockUseCase_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*int32), args[3].(*string))
	})
	return _c
}

func (_c *MockUseCase_GetComments_Call) Return(_a0 *models.CommentConnection, _a1 error) *MockUseCase_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetComments_Call) RunAndReturn(run func(context.Context, string, *int32, *string) (*models.CommentConnection, error)) *MockUseCase_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
