// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function with given fields: ctx, in
func (_m *MockUseCase) CreatePost(ctx context.Context, in models.CreatePostInput) (*models.Post, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreatePostInput) (*models.Post, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreatePostInput) *models.Post); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreatePostInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockUseCase_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.CreatePostInput
func (_e *MockUseCase_Expecter) CreatePost(ctx interface{}, in interface{}) *MockUseCase_CreatePost_Call {
	return &MockUseCase_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, in)}
}

func (_c *MockUseCase_CreatePost_Call) Run(run func(ctx context.Context, in models.CreatePostInput)) *MockUseCase_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreatePostInput))
	})
	return _c
}

func (_c *MockUseCase_CreatePost_Call) Return(_a0 *models.Post, _a1 error) *MockUseCase_CreatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CreatePost_Call) RunAndReturn(run func(context.Context, models.CreatePostInput) (*models.Post, error)) *MockUseCase_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostById provides a mock function with given fields: ctx, postID
func (_m *MockUseCase) GetPostById(ctx context.Context, postID string) (*models.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostById")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetPostById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostById'
type MockUseCase_GetPostById_Call struct {
	*mock.Call
}

// GetPostById is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockUseCase_Expecter) GetPostById(ctx interface{}, postID interface{}) *MockUseCase_GetPostById_Call {
	return &MockUseCase_GetPostById_Call{Call: _e.mock.On("GetPostById", ctx, postID)}
}

func (_c *MockUseCase_GetPostById_Call) Run(run func(ctx context.Context, postID string)) *MockUseCase_GetPostById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUseCase_GetPostById_Call) Return(_a0 *models.Post, _a1 error) *MockUseCase_GetPostById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetPostById_Call) RunAndReturn(run func(context.Context, string) (*models.Post, error)) *MockUseCase_GetPostById_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function with given fields: ctx, first, after
func (_m *MockUseCase) GetPosts(ctx context.Context, first *int32, after *string) (*models.PostConnection, error) {
	ret := _m.Called(ctx, first, after)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 *models.PostConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int32, *string) (*models.PostConnection, error)); ok {
		return rf(ctx, first, after)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int32, *string) *models.PostConnection); ok {
		r0 = rf(ctx, first, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PostConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int32, *string) error); ok {
		r1 = rf(ctx, first, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockUseCase_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - first *int32
//   - after *string
func (_e *MockUseCase_Expecter) GetPosts(ctx interface{}, first interface{}, after interface{}) *MockUseCase_GetPosts_Call {
	return &MockUseCase_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx, first, after)}
}

func (_c *MockUseCase_GetPosts_Call) Run(run func(ctx context.Context, first *int32, after *string)) *MockUseCase_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int32), args[2].(*string))
	})
	return _c
}

func (_c *MockUseCase_GetPosts_Call) Return(_a0 *models.PostConnection, _a1 error) *MockUseCase_GetPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetPosts_Call) RunAndReturn(run func(context.Context, *int32, *string) (*models.PostConnection, error)) *MockUseCase_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// SetPostCommentsAllowed provides a mock function with given fields: ctx, postID, allow
func (_m *MockUseCase) SetPostCommentsAllowed(ctx context.Context, postID string, allow bool) (*models.Post, error) {
	ret := _m.Called(ctx, postID, allow)

	if len(ret) == 0 {
		panic("no return value specified for SetPostCommentsAllowed")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Post, error)); ok {
		return rf(ctx, postID, allow)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *models.Post); ok {
		r0 = rf(ctx, postID, allow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, postID, allow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_SetPostCommentsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPostCommentsAllowed'
type MockUseCase_SetPostCommentsAllowed_Call struct {
	*mock.Call
}

// SetPostCommentsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - allow bool
func (_e *MockUseCase_Expecter) SetPostCommentsAllowed(ctx interface{}, postID interface{}, allow interface{}) *MockUseCase_SetPostCommentsAllowed_Call {
	return &MockUseCase_SetPostCommentsAllowed_Call{Call: _e.mock.On("SetPostCommentsAllowed", ctx, postID, allow)}
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) Run(run func(ctx context.Context, postID string, allow bool)) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) Return(_a0 *models.Post, _a1 error) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_SetPostCommentsAllowed_Call) RunAndReturn(run func(context.Context, string, bool) (*models.Post, error)) *MockUseCase_SetPostCommentsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
