// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Saracomethstein/ozon-test-task/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: ctx, _a1
func (_m *MockUseCase) AddComment(ctx context.Context, _a1 models.Comment) (*models.Comment, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Comment) (*models.Comment, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Comment) *models.Comment); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Comment) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockUseCase_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 models.Comment
func (_e *MockUseCase_Expecter) AddComment(ctx interface{}, _a1 interface{}) *MockUseCase_AddComment_Call {
	return &MockUseCase_AddComment_Call{Call: _e.mock.On("AddComment", ctx, _a1)}
}

func (_c *MockUseCase_AddComment_Call) Run(run func(ctx context.Context, _a1 models.Comment)) *MockUseCase_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Comment))
	})
	return _c
}

func (_c *MockUseCase_AddComment_Call) Return(_a0 *models.Comment, _a1 error) *MockUseCase_AddComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_AddComment_Call) RunAndReturn(run func(context.Context, models.Comment) (*models.Comment, error)) *MockUseCase_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// CheckParentCommentExists provides a mock function with given fields: ctx, parentID
func (_m *MockUseCase) CheckParentCommentExists(ctx context.Context, parentID int64) (int64, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckParentCommentExists")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, parentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CheckParentCommentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckParentCommentExists'
type MockUseCase_CheckParentCommentExists_Call struct {
	*mock.Call
}

// CheckParentCommentExists is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *MockUseCase_Expecter) CheckParentCommentExists(ctx interface{}, parentID interface{}) *MockUseCase_CheckParentCommentExists_Call {
	return &MockUseCase_CheckParentCommentExists_Call{Call: _e.mock.On("CheckParentCommentExists", ctx, parentID)}
}

func (_c *MockUseCase_CheckParentCommentExists_Call) Run(run func(ctx context.Context, parentID int64)) *MockUseCase_CheckParentCommentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUseCase_CheckParentCommentExists_Call) Return(_a0 int64, _a1 error) *MockUseCase_CheckParentCommentExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CheckParentCommentExists_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockUseCase_CheckParentCommentExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPostAllowComments provides a mock function with given fields: ctx, postID
func (_m *MockUseCase) CheckPostAllowComments(ctx context.Context, postID int64) (bool, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPostAllowComments")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CheckPostAllowComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPostAllowComments'
type MockUseCase_CheckPostAllowComments_Call struct {
	*mock.Call
}

// CheckPostAllowComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockUseCase_Expecter) CheckPostAllowComments(ctx interface{}, postID interface{}) *MockUseCase_CheckPostAllowComments_Call {
	return &MockUseCase_CheckPostAllowComments_Call{Call: _e.mock.On("CheckPostAllowComments", ctx, postID)}
}

func (_c *MockUseCase_CheckPostAllowComments_Call) Run(run func(ctx context.Context, postID int64)) *MockUseCase_CheckPostAllowComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUseCase_CheckPostAllowComments_Call) Return(_a0 bool, _a1 error) *MockUseCase_CheckPostAllowComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CheckPostAllowComments_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *MockUseCase_CheckPostAllowComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentPath provides a mock function with given fields: ctx, id
func (_m *MockUseCase) GetCommentPath(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetCommentPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentPath'
type MockUseCase_GetCommentPath_Call struct {
	*mock.Call
}

// GetCommentPath is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUseCase_Expecter) GetCommentPath(ctx interface{}, id interface{}) *MockUseCase_GetCommentPath_Call {
	return &MockUseCase_GetCommentPath_Call{Call: _e.mock.On("GetCommentPath", ctx, id)}
}

func (_c *MockUseCase_GetCommentPath_Call) Run(run func(ctx context.Context, id int64)) *MockUseCase_GetCommentPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUseCase_GetCommentPath_Call) Return(_a0 string, _a1 error) *MockUseCase_GetCommentPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetCommentPath_Call) RunAndReturn(run func(context.Context, int64) (string, error)) *MockUseCase_GetCommentPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsByPost provides a mock function with given fields: ctx, postID, afterCreatedAt, afterID, limit
func (_m *MockUseCase) GetCommentsByPost(ctx context.Context, postID int64, afterCreatedAt *string, afterID int64, limit int32) ([]*models.Comment, error) {
	ret := _m.Called(ctx, postID, afterCreatedAt, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByPost")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)); ok {
		return rf(ctx, postID, afterCreatedAt, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, int64, int32) []*models.Comment); ok {
		r0 = rf(ctx, postID, afterCreatedAt, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *string, int64, int32) error); ok {
		r1 = rf(ctx, postID, afterCreatedAt, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetCommentsByPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsByPost'
type MockUseCase_GetCommentsByPost_Call struct {
	*mock.Call
}

// GetCommentsByPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - afterCreatedAt *string
//   - afterID int64
//   - limit int32
func (_e *MockUseCase_Expecter) GetCommentsByPost(ctx interface{}, postID interface{}, afterCreatedAt interface{}, afterID interface{}, limit interface{}) *MockUseCase_GetCommentsByPost_Call {
	return &MockUseCase_GetCommentsByPost_Call{Call: _e.mock.On("GetCommentsByPost", ctx, postID, afterCreatedAt, afterID, limit)}
}

func (_c *MockUseCase_GetCommentsByPost_Call) Run(run func(ctx context.Context, postID int64, afterCreatedAt *string, afterID int64, limit int32)) *MockUseCase_GetCommentsByPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*string), args[3].(int64), args[4].(int32))
	})
	return _c
}

func (_c *MockUseCase_GetCommentsByPost_Call) Return(_a0 []*models.Comment, _a1 error) *MockUseCase_GetCommentsByPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetCommentsByPost_Call) RunAndReturn(run func(context.Context, int64, *string, int64, int32) ([]*models.Comment, error)) *MockUseCase_GetCommentsByPost_Call {
	_c.Call.Return(run)
	return _c
}

// SetCommentPath provides a mock function with given fields: ctx, id, path
func (_m *MockUseCase) SetCommentPath(ctx context.Context, id int64, path string) error {
	ret := _m.Called(ctx, id, path)

	if len(ret) == 0 {
		panic("no return value specified for SetCommentPath")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUseCase_SetCommentPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommentPath'
type MockUseCase_SetCommentPath_Call struct {
	*mock.Call
}

// SetCommentPath is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - path string
func (_e *MockUseCase_Expecter) SetCommentPath(ctx interface{}, id interface{}, path interface{}) *MockUseCase_SetCommentPath_Call {
	return &MockUseCase_SetCommentPath_Call{Call: _e.mock.On("SetCommentPath", ctx, id, path)}
}

func (_c *MockUseCase_SetCommentPath_Call) Run(run func(ctx context.Context, id int64, path string)) *MockUseCase_SetCommentPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockUseCase_SetCommentPath_Call) Return(_a0 error) *MockUseCase_SetCommentPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUseCase_SetCommentPath_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockUseCase_SetCommentPath_Call {
	_c.Call.Return(run)
	return _c
}

// TotalCountComments provides a mock function with given fields: ctx, postID
func (_m *MockUseCase) TotalCountComments(ctx context.Context, postID int64) (int64, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for TotalCountComments")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_TotalCountComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCountComments'
type MockUseCase_TotalCountComments_Call struct {
	*mock.Call
}

// TotalCountComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockUseCase_Expecter) TotalCountComments(ctx interface{}, postID interface{}) *MockUseCase_TotalCountComments_Call {
	return &MockUseCase_TotalCountComments_Call{Call: _e.mock.On("TotalCountComments", ctx, postID)}
}

func (_c *MockUseCase_TotalCountComments_Call) Run(run func(ctx context.Context, postID int64)) *MockUseCase_TotalCountComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUseCase_TotalCountComments_Call) Return(_a0 int64, _a1 error) *MockUseCase_TotalCountComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_TotalCountComments_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockUseCase_TotalCountComments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
